"""empty message

Revision ID: a1eeec5f5c59
Revises: 
Create Date: 2024-09-12 22:03:25.543626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1eeec5f5c59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login', schema=None) as batch_op:
        batch_op.drop_index('gmail')

    op.drop_table('login')
    with op.batch_alter_table('contact_group', schema=None) as batch_op:
        batch_op.alter_column('group_Number',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('group_Name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('contact_profes', schema=None) as batch_op:
        batch_op.alter_column('member_Prefix',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('member_Name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('member_Lname',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('member_Facebook',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.alter_column('branchIT',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('branchCS',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.alter_column('branchCS',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
        batch_op.alter_column('branchIT',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)

    with op.batch_alter_table('contact_profes', schema=None) as batch_op:
        batch_op.alter_column('member_Facebook',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('member_Lname',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('member_Name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('member_Prefix',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('contact_group', schema=None) as batch_op:
        batch_op.alter_column('group_Name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('group_Number',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(display_width=11),
               nullable=False)

    op.create_table('login',
    sa.Column('idLogin', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('userName', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('passWord', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('gmail', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('role', mysql.ENUM('admin', 'professor', 'student'), nullable=False),
    sa.PrimaryKeyConstraint('idLogin'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('login', schema=None) as batch_op:
        batch_op.create_index('gmail', ['gmail'], unique=True)

    # ### end Alembic commands ###
